#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only

build() {
    local applet

    add_binary /usr/lib/initcpio/busybox /bin/busybox

    for applet in $(/usr/lib/initcpio/busybox --list); do
        add_symlink "/usr/bin/$applet" busybox
    done

    # add kmod with applet symlinks
    add_binary kmod
    for applet in {dep,ins,rm,ls}mod mod{probe,info}; do
        add_symlink "/usr/bin/$applet" kmod
    done

    add_binary blkid
    add_binary mount
    add_binary switch_root

    local MKINITCPIO_CONFIG_PATH="/opt/turboarch/ramdisk-installer"

    add_file "$MKINITCPIO_CONFIG_PATH/init_functions" "/init_functions"
    add_file "$MKINITCPIO_CONFIG_PATH/init" "/init"
	
    local BINARIES_PATH="/opt/turboarch/bin/"
    
    add_module ntfs3
    add_binary "$BINARIES_PATH/chkufsd" /usr/bin/chkufsd
    add_binary "$BINARIES_PATH/fsck.ntfs" /usr/bin/fsck.ntfs

    add_module vfat
    add_binary tar
    add_binary gzip
}

help() {
    cat <<HELPEOF
TurboArch replacement for base hook.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
